### PR TITLE
Making safestrings functions usable

### LINKED ISSUE #100: SafeStrings.js doesn't work
Currently, SafeStrings.js is written as follows:

```// Function to make paths safe that are used in an input
var safeStringInput = function(string) {
  var safeString = string;

  // Safen the string
  // \ will be \\
  safeString.replace(/\\/g, '\\\\');

  // : will be \:
  safeString.replace(/\:/g, '\\:');

  // Return safe string
  return safeString;
}

// Function to make string safe that are used in a filter
var safeStringFilter = function(string) {
  var safeString = string;

  // Safen the string
  // \ will be \\
  safeString.replace(/\\/g, '\\\\');

  // : will be \:
  safeString.replace(/\:/g, '\\:');

  // ' will be \'
  safeString.replace(/\'/g, '\\\'');

  // Return safe string
  return safeString;
}

module.exports = {
  forInput: safeStringInput,
  forFilter: safeStringFilter
}
```

it should be this: 

```// Function to make paths safe that are used in an input
var safeStringInput = function(string) {
  var safeString = string;

  // Safen the string
  // \ will be \\
  safeString = safeString.replace(/\\/g, '\\\\');

  // : will be \:
  safeString = safeString.replace(/\:/g, '\\:');

  // Return safe string
  return safeString;
}

// Function to make string safe that are used in a filter
var safeStringFilter = function(string) {
  var safeString = string;

  // Safen the string
  // \ will be \\
  safeString = safeString.replace(/\\/g, '\\\\');

  // : will be \:
  safeString = safeString.replace(/\:/g, '\\:');

  // ' will be \'
  safeString = safeString.replace(/\'/g, '\\\'');

  // Return safe string
  return safeString;
}

module.exports = {
  forInput: safeStringInput,
  forFilter: safeStringFilter
}
```

(safeString isn't actually being reassigned to the replaced string.)

### PR DESCRIPTION
**Pull request by AndreasWebdev**
Fixes #100

### CODE REVIEW

File: src/stream/safeStrings.js [hunk 1]
```diff
@@ -4,10 +4,10 @@ var safeStringInput = function(string) {
 
   // Safen the string
   // \ will be \\
-  safeString.replace(/\\/g, '\\\\');
+  safeString = safeString.replace(/\\/g, '\\\\');
```
Comment (torch2424) [inline src/stream/safeStrings.js]: Oops haha! 🙃
